# Generated by Django 2.1.3 on 2018-12-20 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_name', models.CharField(max_length=10)),
                ('car_price', models.CharField(max_length=10)),
                ('car_3D', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarSystem',
            fields=[
                ('car_system_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_system_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('car_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_type_name', models.CharField(max_length=10)),
                ('car_type_all_name', models.CharField(max_length=30)),
                ('car_type_img', models.ImageField(upload_to='Car_type/')),
                ('car_system_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.CarSystem')),
            ],
        ),
        migrations.CreateModel(
            name='CarTypeBaseInfo',
            fields=[
                ('car_type_base_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('src', models.ImageField(upload_to='CarTypeBaseInfo/')),
            ],
        ),
        migrations.CreateModel(
            name='CarTypeBaseName',
            fields=[
                ('car_type_base_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_type_base_name', models.CharField(max_length=10)),
                ('herf', models.CharField(blank=True, max_length=50, null=True)),
                ('belong_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.CarType')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('distributor_id', models.AutoField(primary_key=True, serialize=False)),
                ('distributor_name', models.CharField(blank=True, max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=12)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('belong_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.City')),
            ],
        ),
        migrations.CreateModel(
            name='MainNav',
            fields=[
                ('main_nav_id', models.AutoField(primary_key=True, serialize=False)),
                ('main_nav_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MainOneNav',
            fields=[
                ('main_one_nav', models.AutoField(primary_key=True, serialize=False)),
                ('main_one_nav_name', models.CharField(max_length=10)),
                ('main_one_nav_img', models.ImageField(blank=True, null=True, upload_to='OneNav/')),
                ('main_one_nav_title', models.CharField(blank=True, max_length=50, null=True)),
                ('belong_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.MainNav')),
            ],
        ),
        migrations.CreateModel(
            name='MainTwoNav',
            fields=[
                ('main_two_nav', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('src', models.ImageField(blank=True, null=True, upload_to='detail_layout/')),
                ('content', models.TextField(blank=True, default='暂无记录', null=True)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('brief', models.CharField(blank=True, max_length=255, null=True)),
                ('belong_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.MainOneNav')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_id', models.AutoField(primary_key=True, serialize=False)),
                ('province_name', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='SlideshowWrapper',
            fields=[
                ('slideshow_wrapper_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=30)),
                ('content', models.CharField(blank=True, max_length=255)),
                ('src', models.ImageField(blank=True, upload_to='rotation_chart/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('user_name', models.CharField(blank=True, max_length=10, null=True)),
                ('telephone', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('sex', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('month_salary', models.CharField(blank=True, max_length=10, null=True)),
                ('id_card', models.CharField(blank=True, max_length=18, null=True)),
                ('belong_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Distributor')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('user_type', models.AutoField(primary_key=True, serialize=False)),
                ('user_type_name', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserType'),
        ),
        migrations.AddField(
            model_name='city',
            name='belong_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Province'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.CarType'),
        ),
    ]
