# Generated by Django 2.1.3 on 2018-12-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_cartypebaseinfo_belong_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartypebaseinfo',
            name='content',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
