# Generated by Django 2.1.3 on 2018-12-21 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_mainonenav_main_one_nav_brief'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetailInfo',
            fields=[
                ('car_detail_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_detail_info_name', models.CharField(max_length=20)),
                ('car_detail_info', models.CharField(max_length=20)),
                ('belong_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.CarTypeBaseName')),
            ],
        ),
    ]
