# Generated by Django 2.1.3 on 2018-12-21 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_carinfodetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetailInfoName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('belong_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.CarTypeBaseName')),
            ],
        ),
        migrations.CreateModel(
            name='CarInfoDetailName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('belong_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.CarInfo')),
            ],
        ),
        migrations.AlterField(
            model_name='cardetailinfo',
            name='belong_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.CarDetailInfoName'),
        ),
        migrations.AlterField(
            model_name='carinfodetail',
            name='belong_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.CarInfoDetailName'),
        ),
    ]
