# Generated by Django 2.1.3 on 2018-12-21 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20181221_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetailinfoname',
            name='belong_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.CarType'),
        ),
    ]
