# Generated by Django 2.1.3 on 2018-12-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20181221_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='car_name',
            field=models.CharField(max_length=20),
        ),
    ]
