# Generated by Django 2.1.3 on 2018-12-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_orderdrive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdrive',
            name='confirm',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
