# Generated by Django 2.1.3 on 2018-12-23 04:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20181223_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdrive',
            name='feedback_time',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='orderdrive',
            name='plan_time',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='orderdrive',
            name='order_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
