# Generated by Django 2.1.3 on 2018-12-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_orderdrive_confirm_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_card',
        ),
        migrations.RemoveField(
            model_name='user',
            name='month_salary',
        ),
        migrations.AddField(
            model_name='orderdrive',
            name='id_card',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='orderdrive',
            name='month_salary',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
