# Generated by Django 2.1.3 on 2018-12-26 07:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20181225_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyCar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=10)),
                ('car_name', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=2)),
                ('telephone', models.CharField(max_length=11)),
                ('dealer', models.CharField(max_length=30)),
                ('buy_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_pay', models.CharField(max_length=10)),
                ('month_pay', models.CharField(max_length=10)),
                ('month_salary', models.CharField(max_length=10)),
                ('id_card', models.CharField(max_length=18)),
                ('bank_card', models.CharField(max_length=19)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='orderdrive',
            name='id_card',
        ),
        migrations.RemoveField(
            model_name='orderdrive',
            name='month_salary',
        ),
    ]
